import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#ea580c",
        "surface-dim": "#94a3b8",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fdfcff",
        primary: "#0e7490",
        "inverse-on-surface": "#e8eef5",
        "secondary-fixed-dim": "#fdba74",
        "surface-container-high": "#e2e8f0",
        "on-background": "#0b1220",
        "on-tertiary-fixed-variant": "#314865",
        "on-secondary-fixed": "#311300",
        "primary-fixed": "#cffafe",
        "on-primary-fixed": "#083344",
        outline: "#64748b",
        "on-error-container": "#93000a",
        secondary: "#c2410c",
        "inverse-surface": "#0f172a",
        background: "#f4f6f9",
        error: "#ba1a1a",
        "surface-bright": "#ffffff",
        "tertiary-fixed-dim": "#b0c8eb",
        "secondary-fixed": "#ffdbc7",
        "surface-container": "#e8ecf2",
        "surface-container-low": "#eef1f6",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e8ecf2",
        "on-secondary": "#ffffff",
        "outline-variant": "#bfc7d3",
        "tertiary-container": "#5f7695",
        "on-primary-fixed-variant": "#004a79",
        "on-surface-variant": "#404751",
        "on-secondary-fixed-variant": "#733600",
        "inverse-primary": "#9acbff",
        "on-primary-container": "#fdfcff",
        "surface-container-highest": "#dae2fd",
        "error-container": "#ffdad6",
        "primary-container": "#0891b2",
        surface: "#f4f6f9",
        "primary-fixed-dim": "#67e8f9",
        "on-tertiary-fixed": "#001c37",
        "surface-tint": "#0e7490",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d2e4ff",
        tertiary: "#334155",
        "on-secondary-container": "#652e00",
        "on-surface": "#0b1220",
        accent: "#0f766e",
        gray: {
          50: "#f9fafb",
          100: "#f3f4f6",
          200: "#e5e7eb",
          300: "#d1d5db",
          400: "#9ca3af",
          500: "#6b7280",
          600: "#4b5563",
          700: "#374151",
          800: "#1f2937",
          900: "#111827",
          950: "#030712",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        margin: "3rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        display: ["var(--font-display)", "Plus Jakarta Sans", "sans-serif"],
        "sans-bs": ["var(--font-sans)", "DM Sans", "sans-serif"],
        "display-hero": ["var(--font-display)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-display)", "Plus Jakarta Sans", "sans-serif"],
        caption: ["var(--font-sans)", "DM Sans", "sans-serif"],
        "body-lg": ["var(--font-sans)", "DM Sans", "sans-serif"],
        "body-md": ["var(--font-sans)", "DM Sans", "sans-serif"],
        "body-sm": ["var(--font-sans)", "DM Sans", "sans-serif"],
        "headline-lg": ["var(--font-display)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-display)", "Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["var(--font-display)", "Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": [
          "var(--font-display)",
          "Plus Jakarta Sans",
          "sans-serif",
        ],
        "headline-lg-mobile": [
          "var(--font-display)",
          "Plus Jakarta Sans",
          "sans-serif",
        ],
        "label-md": ["var(--font-sans)", "DM Sans", "sans-serif"],
        "title-md": ["var(--font-sans)", "DM Sans", "sans-serif"],
        "label-sm": ["var(--font-sans)", "DM Sans", "sans-serif"],
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        shimmer: "shimmer 1.5s ease-in-out infinite",
      },
      backgroundImage: {
        shimmer:
          "linear-gradient(90deg, rgba(218,226,253,0.4) 0%, rgba(255,255,255,0.9) 50%, rgba(218,226,253,0.4) 100%)",
      },
      fontSize: {
        "display-hero": [
          "56px",
          { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" },
        ],
        "headline-md": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        caption: [
          "10px",
          { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" },
        ],
        "body-md": [
          "15px",
          { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-sm": [
          "13px",
          { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "headline-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" },
        ],
        "title-lg": [
          "18px",
          { lineHeight: "26px", letterSpacing: "0em", fontWeight: "600" },
        ],
        "display-hero-mobile": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" },
        ],
        "title-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
